// Questo è il database COMPLETO di tutte le frasi del gioco.

// --- 1. ROUND STANDARD (Contiene Mondo, Musica, Mistero, Express, Ultimo) ---
const phrasesDB = [
    // === (A) MONDO: Nozioni ===
    { category: "Parigi: Louvre", solution: "CUSTODISCE IL SORRISO DELLA GIOCONDA" },
    { category: "Londra: Big Ben", solution: "L'OROLOGIO SIMBOLO DELLA CITTÀ CHE SVETTA ACCANTO AL PARLAMENTO" },
    { category: "Pisa: Torre Pendente", solution: "UN CAMPANILE FAMOSO PERCHÉ SFIDA LA GRAVITÀ" },
    { category: "New York: Statua della Libertà", solution: "SIMBOLO D'AMERICA DONATO DALLA FRANCIA" },
    { category: "Egitto: Sfinge", solution: "HA IL CORPO DI LEONE E LA TESTA UMANA" },
    { category: "Venezia: Gondola", solution: "ROMANTICA IMBARCAZIONE CHE SCIVOLA TRA I CANALI" },
    { category: "Cina: Grande Muraglia", solution: "LUNGHISSIMA FORTIFICAZIONE CHE ATTRAVERSA IL PAESE" },
    { category: "Roma: Fontana di Trevi", solution: "SI LANCIA UNA MONETINA PER POTERCI TORNARE" },
    { category: "Brasile: Carnevale", solution: "SFILATE DI SAMBA E CARRI ALLEGORICI A RIO" },
    { category: "India: Taj Mahal", solution: "MAUSOLEO DI MARMO BIANCO COSTRUITO PER AMARE" },
    { category: "Australia: Canguro", solution: "MARSUPIALE CHE SALTA NEL DESERTO ROSSO" },
    { category: "Giappone: Sushi", solution: "RISO E PESCE CRUDO SERVITI CON ARTE" },
    { category: "Messico: Tacos", solution: "TORTILLAS DI MAIS RIPIENE E SPESSO PICCANTI" },
    { category: "Napoli: Pizza Margherita", solution: "POMODORO MOZZARELLA E BASILICO PER OMAGGIARE LA REGINA" },
    { category: "Spagna: Flamenco", solution: "BALLO ANDALUSO ACCOMPAGNATO DA CHITARRA E NACCHERE" },
    { category: "Grecia: Partenone", solution: "TEMPIO SIMBOLO DELL'ANTICA ATENE COSTRUITO IN ONORE DI ATENA" },
    { category: "Olanda: Tulipani", solution: "CAMPI COLORATISSIMI CHE SBOCCIANO IN PRIMAVERA NEI PAESI BASSI" },
    { category: "Russia: Matrioska", solution: "BAMBOLA DI LEGNO CHE NE CONTIENE MOLTE ALTRE" },
    { category: "Scozia: Kilt", solution: "IL TRADIZIONALE GONNELLINO A QUADRI DEGLI UOMINI" },
    { category: "Svizzera: Cioccolato", solution: "DOLCE PRELIBATEZZA FAMOSA IN TUTTO IL MONDO" },
    { category: "Berlino: Porta di Brandeburgo", solution: "MONUMENTO SIMBOLO DELLA GERMANIA UNITA" },
    { category: "Argentina: Tango", solution: "BALLO PASSIONALE NATO A BUENOS AIRES" },
    { category: "Canada: Sciroppo d'acero", solution: "CONDIMENTO DOLCE VERSATO SUI PANCAKE CALDI" },
    { category: "Marocco: Souk", solution: "MERCATO LABIRINTICO GREMITO DI SPEZIE E STOFFE" },
    { category: "Turchia: Grand Bazaar", solution: "UNO DEI MERCATI COPERTI PIÙ GRANDI DEL MONDO" },
    { category: "Perù: Machu Picchu", solution: "ARROCCATA SULLE ANDE E CONOSCIUTA DA TUTTI COME LA CITTÀ PERDUTA DEGLI INCA" },
    { category: "Kenya: Safari", solution: "VIAGGIO PER OSSERVARE GLI ANIMALI LIBERI IN SAVANA" },
    { category: "Irlanda: Trifoglio", solution: "SIMBOLO VERDE DI SAN PATRIZIO E PORTAFORTUNA" },
    { category: "Vienna: Valzer", solution: "DANZA ELEGANTE CHE RISUONA NEI SALONI IMPERIALI" },
    { category: "Cuba: Sigari", solution: "FOGLIE DI TABACCO ARROTOLATE A MANO CON CURA" },
    { category: "Islanda: Geyser", solution: "GETTO D'ACQUA BOLLENTE CHE ESPLODE DAL TERRENO" },
    { category: "Norvegia: Fiordi", solution: "BRACCI DI MARE CHE SI INSINUANO TRA ALTE SCOGLIERE" },
    { category: "Ungheria: Gulasch", solution: "ZUPPA DI CARNE INSAPORITA CON PAPRIKA" },
    { category: "Portogallo: Azulejos", solution: "PIASTRELLE DI CERAMICA BLU FINEMENTE DECORATE" },
    { category: "Belgio: Waffle", solution: "CIALDA DOLCE A SCACCHIERA SERVITA CALDA" },
    { category: "Thailandia: Tuk Tuk", solution: "TAXI A TRE RUOTE RUMOROSO E VELOCISSIMO" },
    { category: "Vietnam: Cappello a cono", solution: "PROTEGGE I CONTADINI DAL SOLE E DALLA PIOGGIA" },
    { category: "Giordania: Petra", solution: "CITTÀ ANTICA SCAVATA NELLA ROCCIA ROSA" },
    { category: "Praga: Ponte Carlo", solution: "STORICO ATTRAVERSAMENTO PEDONALE ADORNATO DI STATUE" },
    { category: "San Francisco: Golden Gate", solution: "IL PONTE SOSPESO ROSSO CHE DOMINA LA BAIA" },
    { category: "Hollywood: Walk of Fame", solution: "MARCIAPIEDE CON LE STELLE DEDICATE AI DIVI" },
    { category: "Las Vegas: Casinò", solution: "LUCI AL NEON E SLOT MACHINE NEL MEZZO DEL DESERTO" },
    { category: "Milano: Duomo", solution: "CATTEDRALE GOTICA SORMONTATA DALLA MADONNINA D'ORO" },
    { category: "Sicilia: Cannolo", solution: "CIALDA FRITTA RIPIENA DI RICOTTA DOLCE" },
    { category: "Finlandia: Sauna", solution: "BAGNO DI VAPORE PER RILASSARE CORPO E MENTE" },
    { category: "Mosca: Piazza Rossa", solution: "CUORE STORICO E POLITICO DELLA CAPITALE RUSSA" },
    { category: "Polinesia: Bungalow", solution: "CASETTA SU PALAFITTE SOSPESA SULL'ACQUA TURCHESE" },
    { category: "Sahara", solution: "DISTESA INFINITA DI DUNE CHE ATTRAVERSA IL NORD AFRICA" },
    { category: "Transilvania: Castello", solution: "DIMORA LEGGENDARIA ASSOCIATA AL CONTE DRACULA" },
    { category: "Monaco: Oktoberfest", solution: "GRANDE FESTA DELLA BIRRA CHE ANIMA L'AUTUNNO" },
    { category: "Valencia: Paella", solution: "RISO ALLO ZAFFERANO COTTO NELLA TRADIZIONALE PADELLA LARGA" },
    { category: "Svezia: Ikea", solution: "MOBILI DA MONTARE SEGUENDO ISTRUZIONI MINIMALISTE" },
    { category: "Polo Nord: Igloo", solution: "CUPOLA DI NEVE COSTRUITA DALLE POPOLAZIONI ARTICHE" },
    { category: "Cile: Isola di Pasqua", solution: "GIGANTI DI PIETRA SCOLPITI DAL POPOLO RAPA NUI" },
    { category: "Madagascar: Lemure", solution: "PRIMATE DAL MUSO CURIOSO CON CODA AD ANELLI BIANCHI E NERI" },
    { category: "Antartide: Pinguino", solution: "UCCELLO ELEGANTE CHE CAMMINA ONDEGGIANDO SUL GHIACCIO" },
    { category: "Napoli: Presepe", solution: "ARTE PRESEPIALE TRADIZIONALE DI SAN GREGORIO ARMENO" },
    { category: "Verona: Arena", solution: "ANFITEATRO ROMANO CELEBRE PER GLI SPETTACOLI LIRICI" },
    { category: "Bologna: Tortellini", solution: "PASTA RIPIENA CHIUSA A FORMA DI PICCOLO OMBELICO" },
    { category: "Genova: Pesto", solution: "SALSA VERDE CON BASILICO PINOLI E OLIO LIGURE" },
    { category: "Firenze: Ponte Vecchio", solution: "ANTICO PONTE SULL'ARNO COSTELLATO DI BOTTEGHE ORAFE" },
    { category: "Siena: Palio", solution: "CORSA DI CAVALLI NELLA STORICA PIAZZA DEL CAMPO" },
    { category: "Lisbona: Tram Giallo", solution: "CARROZZA VINTAGE CHE SALE TRA VICOLI RIPIDI E STRETTI" },
    { category: "Barcellona: Sagrada Familia", solution: "BASILICA ANCORA INCOMPIUTA FIRMATA DA ANTONI GAUDÍ" },
    { category: "Atene: Acropoli", solution: "LA CITTÀ ALTA CHE CUSTODISCE I TEMPLI DELL'ANTICA GRECIA" },
    { category: "Dubai: Burj Khalifa", solution: "IL GRATTACIELO PIÙ ALTO MAI COSTRUITO" },
    { category: "Maldive: Atollo", solution: "ANELLO DI CORALLO CHE CIRCONDA LAGUNE TURCHESI" },
    { category: "Tibet: Monaco", solution: "RELIGIOSO BUDDHISTA CON TUNICA ROSSA E PREGHIERE RITUALI" },
    { category: "Nepal: Everest", solution: "LA CIMA PIÙ ALTA DEL PIANETA CON I SUOI OTTOMILA METRI" },
    { category: "Amazzonia: Foresta", solution: "DISTESA VERDE CONSIDERATA IL POLMONE DELLA TERRA" },
    { category: "Panama: Canale", solution: "VIA ARTIFICIALE CHE COLLEGA L'ATLANTICO AL PACIFICO" },
    { category: "Texas: Cowboy", solution: "CAVALLERIZZO DEI RANCH CON CAPPELLO A TESA LARGA" },
    { category: "New Orleans: Jazz", solution: "MUSICA NATA NEI LOCALI DELLA COMUNITÀ AFROAMERICANA" },
    { category: "Miami: Spiaggia", solution: "ARENILE FAMOSO PER TORRETTE IN STILE ART DÉCO" },
    { category: "Chicago: Windy City", solution: "SOPRANNOME NATO DAI DISCORSI POLITICI ENFATICI DELL'OTTOCENTO" },
    { category: "Madrid: Plaza Mayor", solution: "GRANDE PIAZZA PORTICATA CUORE DELLA VITA CITTADINA" },
    { category: "Kenya: Masai Mara", solution: "RISERVA NATURALE FAMOSA PER LA MIGRAZIONE DEGLI GNU" },
    { category: "Cina: Panda Gigante", solution: "ORSO BIANCO E NERO SIMBOLO DELLA CONSERVAZIONE MONDIALE" },
    { category: "Austria: Danubio", solution: "FIUME CELEBRATO DAL CELEBRE VALZER DI STRAUSS" },
    { category: "Marocco: Menta", solution: "FOGLIE PROFUMATE USATE PER IL TRADIZIONALE TÈ DOLCE" },
    { category: "Egitto: Nilo", solution: "FIUME CHE HA RESO FERTILE LA CIVILTÀ DEI FARAONI" },
    { category: "Giappone: Monte Fuji", solution: "VULCANO SACRO DALLA CIMA PERFETTAMENTE CONICA" },
    { category: "Francia: Mont Saint-Michel", solution: "ABBAZIA MEDIEVALE CHE EMERGE DALLE MAREE" },
    { category: "Germania: Birra", solution: "BEVANDA PRODOTTA SECONDO L'ANTICA LEGGE DELLA PUREZZA" },
    { category: "Islanda: Aurore", solution: "LUCI DANZANTI CHE ILLUMINANO IL CIELO NOTTURNO" },
    { category: "Brasile: Amazzonia", solution: "REGIONE RICCA DI BIODIVERSITÀ UNICA AL MONDO" },
    { category: "Messico: Sombrero", solution: "CAPPELLO MOLTO LARGO USATO PER RIPARARSI DAL SOLE" },
    { category: "Turchia: Cappadocia", solution: "PAESAGGI LUNARI CON MONGOLFIERE ALL'ALBA" },
    { category: "Scozia: Castelli", solution: "ANTICHE FORTEZZE IN PIETRA IMMERSE NELLE BRUGHIERE" },
    { category: "Australia: Opera House", solution: "TEATRO DALLE VELE BIANCHE SIMBOLO DI SYDNEY" },
    { category: "Israele: Mar Morto", solution: "ACQUA SALATISSIMA CHE PERMETTE DI GALLEGGIARE SENZA SFORZO" },
    { category: "Canada: Niagara", solution: "CASCATE IMPONENTI AL CONFINE CON GLI STATI UNITI" },
    { category: "India: Taj Lake Palace", solution: "PALAZZO BIANCO CHE SEMBRA GALLEGGIARE SUL LAGO PICHOLA" },
    { category: "Russia: Transiberiana", solution: "IL VIAGGIO IN TRENO PIÙ LUNGO DEL MONDO" },
    { category: "Kenya: Kilimangiaro", solution: "VETTA INNEVATA CHE DOMINA LA SAVANA AFRICANA" },
    { category: "Norvegia: Sole di mezzanotte", solution: "IL SOLE RESTA VISIBILE ANCHE A NOTTE FONDA D'ESTATE" },
    { category: "Italia: Cinque Terre", solution: "BORGHI COLORATI ARROCCATI SULLE SCOGLIERE LIGURI" },

    // === (B) MONDO: Curiosità ===
    { category: "Galles: Llanfairpwllgwyngyll", solution: "UNA CITTADINA CON UNO DEI NOMI PIÙ LUNGHI D'EUROPA" },
    { category: "Giappone: Inemuri", solution: "DORMIRE IN UFFICIO È ACCETTATO COME PROVA DI DEDIZIONE" },
    { category: "Singapore: Chewing Gum", solution: "LA VENDITA DELLE GOMME DA MASTICARE È VIETATA PER LEGGE" },
    { category: "Finlandia: Trasporto moglie", solution: "GARA BIZZARRA IN CUI SI CORRE PORTANDO LA PARTNER IN SPALLA" },
    { category: "Spagna: La Tomatina", solution: "BATTAGLIA CITTADINA IN CUI SI LANCIANO POMODORI MATURI" },
    { category: "Bhutan: Felicità Interna Lorda", solution: "IL PAESE MISURA IL BENESSERE INVECE DEL PIL" },
    { category: "Islanda: Strade", solution: "ALCUNI PERCORSI VENGONO DEVIATI PER RISPETTARE LE ROCCE DEGLI ELFI" },
    { category: "Thailandia: Lopburi", solution: "CITTÀ DOVE SI ORGANIZZA UN BUFFET DI FRUTTA PER LE SCIMMIE" },
    { category: "Seattle: Gum Wall", solution: "UN MURO INTERAMENTE RICOPERTO DI GOMME DA MASTICARE" },
    { category: "Repubblica Ceca: Pasqua", solution: "PER TRADIZIONE GLI UOMINI FRUSTANO SIMBOLICAMENTE LE DONNE CON RAMI DI SALICE" },
    { category: "Giappone: Angurie", solution: "ALCUNE VENGONO COLTIVATE IN FORMA QUADRATA PER FACILITARNE LA CONSERVAZIONE" },
    { category: "Svezia: Icehotel", solution: "ALBERGO SCOLPITO NEL GHIACCIO CHE SI SCIOGLIE OGNI PRIMAVERA" },
    { category: "Bolivia: Mercato delle Streghe", solution: "SI VENDONO FETI DI LAMA ESSICCATI COME TALISMANI" },
    { category: "Turchia: Dondurma", solution: "GELATO ELASTICO E FILANTE CHE NON SI SCIOGLIE FACILMENTE" },
    { category: "Marocco: Capre", solution: "SI ARRAMPICANO SUGLI ALBERI DI ARGAN PER MANGIARNE I FRUTTI" },
    { category: "Norvegia: il Sole", solution: "IN ESTATE NON TRAMONTA PER SETTIMANE" },
    { category: "India: Tempio Karni Mata", solution: "SANTUARIO ABITATO DA MIGLIAIA DI TOPI CONSIDERATI SACRI" },
    { category: "Cina: Uova centenarie", solution: "CONSERVATE PER MESI IN UNA MISCELA ALCALINA" },
    { category: "Etiopia: Calendario", solution: "L'ANNO È COMPOSTO DA TREDICI MESI CON UN RITARDO DI SETTE ANNI" },
    { category: "Giappone: Okunoshima", solution: "ISOLA POPOLATA DA CENTINAIA DI CONIGLI SELVATICI" },
    { category: "Ohio: Longaberger", solution: "EDIFICIO PER UFFICI COSTRUITO A FORMA DI ENORME CESTINO" },
    { category: "Vietnam: Egg Coffee", solution: "CAFFÈ MESCOLATO CON TUORLO D'UOVO MONTATO E ZUCCHERO" },
    { category: "Corea del Sud: Inchiostro rosso", solution: "SCRIVERE IL NOME DI QUALCUNO CON il rosso È CONSIDERATO DI CATTIVO AUSPICIO" },
    { category: "Francia: Maiale", solution: "UN'ANTICA LEGGE VIETAVA DI CHIAMARE UN MAIALE NAPOLEONE" },
    { category: "Australia: Lago Hillier", solution: "LAGO NATURALMENTE ROSA PER LA PRESENZA DI ALGHE E MICRORGANISMI" },
    { category: "Grecia: Tacchi a spillo", solution: "VIETATI NEI SITI ARCHEOLOGICI PER PROTEGGERE I PAVIMENTI ANTICHI" },
    { category: "Polonia: Casa capovolta", solution: "ATTRAZIONE COSTRUITA COMPLETAMENTE A TESTA IN GIÙ" },
    { category: "Messico: Isola delle Bambole", solution: "ALBERI DECORATI CON BAMBOLE PER SCACCIARE GLI SPIRITI MALIGNI" },
    { category: "Germania: Autobahn", solution: "TRATTI AUTOSTRADALI SENZA LIMITE DI VELOCITÀ" },
    { category: "Giappone: Oshiya", solution: "ADDETTI CHE SPINGONO I PASSEGGERI NEI VAGONI AFFOLLATI" },
    { category: "Scozia: Haggis", solution: "PIATTO TRADIZIONALE CUCINATO DENTRO LO STOMACO DI UNA PECORA" },
    { category: "Sardegna: Casu Marzu", solution: "FORMAGGIO PECORINO CHE CONTIENE LARVE VIVE" },
    { category: "California: Bodie", solution: "CITTÀ FANTASMA DEL FAR WEST RIMASTA INTATTA NEL TEMPO" },
    { category: "Cina: Bacchette", solution: "INFIGGERLE VERTICALMENTE NEL RISO RICHIAMA I RITUALI FUNEBRI" },
    { category: "Amsterdam: Case storte", solution: "EDIFICI INCLINATI PERCHÉ LE TASSE DIPENDEVANO DALLA LARGHEZZA DELLA FACCIATA" },
    { category: "Canada: Prigione degli orsi", solution: "STRUTTURA DOVE SI TRATTENGONO TEMPORANEAMENTE GLI ORSI POLARI CATTIVI" },
    { category: "India: Ufficio postale", solution: "L'UNICO AL MONDO COSTRUITO SU UNA BARCA NEL LAGO DAL" },
    { category: "Mosca: Metropolitana", solution: "STAZIONI DECORATE COME SALONI REALI CON LAMPADARI E MOSAICI" },
    { category: "Nuova Zelanda: Collina", solution: "NOME MAORI LUNGHISSIMO COMPOSTO DA OTTANTACINQUE LETTERE" },
    { category: "Spagna: Siesta", solution: "TRADIZIONE DI CHIUDERE I NEGOZI NEL PRIMO POMERIGGIO PER RIPOSARE" },
    { category: "Giappone: Water", solution: "GABINETTI TECNOLOGICI CON SEDILE RISCALDATO E FUNZIONE LAVANTE" },
    { category: "Colombia: Formiche", solution: "LE CULONAS VENGONO SERVITE FRITTE COME SNACK CROCCANTE" },
    { category: "Portogallo: Libreria Lello", solution: "SCALA INTERNA TALMENTE SCENOGRAFICA DA RICORDARE HARRY POTTER" },
    { category: "Inghilterra: Cheese Rolling", solution: "GARA SPERICOLATA DOVE SI INSEGUE UNA FORMA DI FORMAGGIO GIÙ DA UNA COLLINA" },
    { category: "Filippine: Bare sospese", solution: "LE BARE VENGONO APPESE ALLE PARETI ROCCIOSE DELLE MONTAGNE" },
    { category: "Cina: Ingorgo", solution: "UN BLOCCO STRADALE RIMASE FERMO PER OLTRE DIECI GIORNI CONSECUTIVI" },
    { category: "Svezia: Surstromming", solution: "ARINGA FERMENTATA FAMOSA PER IL SUO ODORE FORTISSIMO" },
    { category: "Bahamas: Pig Beach", solution: "SPIAGGIA DOVE SI NUOTA ACCANTO AI MAIALI" },
    { category: "Alberobello: Trulli", solution: "CASE CONICHE IN PIETRA BIANCA UNICHE AL MONDO" },
    { category: "Nevada: Bottle House", solution: "ABITAZIONE COSTRUITA CON CENTINAIA DI BOTTIGLIE DI VETRO" },
    { category: "Vietnam: Train Street", solution: "BINARI STRETTISSIMI DOVE IL TRENO PASSA A POCHI CENTIMETRI DALLE CASE" },
    { category: "Egitto: Clacson", solution: "GLI AUTOMOBILISTI COMUNICANO TRA LORO USANDOLO COME LINGUAGGIO" },
    { category: "Finlandia: Saune", solution: "IN PROPORZIONE PIÙ SAUNE CHE AUTOMOBILI IN TUTTO IL PAESE" },
    { category: "Giappone: KitKat", solution: "ESISTONO CENTINAIA DI GUSTI PARTICOLARI DAL WASABI ALLA PATATA DOLCE" },
    { category: "Messico: Vulcano Cuexcomate", solution: "CONSIDERATO UN VULCANO IN REALTÀ È UN GEYSER SPENTO ALTO TREDICI METRI" },
    { category: "Ucraina: Tunnel dell'Amore", solution: "GALLERIA NATURALE FORMATA DAGLI ALBERI LUNGO I BINARI" },
    { category: "Taiwan: Modern Toilet", solution: "RISTORANTE DOVE IL CIBO È SERVITO IN MINI WATER DI CERAMICA" },
    { category: "Danimarca: Christiania", solution: "QUARTIERE AUTOGESTITO CON REGOLE PROPRIE" },
    { category: "San Pietroburgo: Gatti", solution: "L'HERMITAGE LI OSPITA PER PROTEGGERE LE OPERE DAI TOPI" },
    { category: "Turchia: Caffè", solution: "LA LETTURA DEI FONDI È CONSIDERATA UNA FORMA DI DIVINAZIONE" },
    { category: "Irlanda: Halloween", solution: "LA FESTA DELLE ZUCCHE NASCE DALL'ANTICO SAMHAIN CELTICO" },
    { category: "Thailandia: Donne Giraffa", solution: "INDOSSANO ANELLI DI OTTONE PER ALLUNGARE VISIVAMENTE IL COLLO" },
    { category: "Ecuador: Altalena", solution: "SI DONDOLA SOPRA UN PRECIPIZIO DALLA CASA DELL'ALBERO" },
    { category: "Australia: Natale", solution: "CADE D'ESTATE E SI FESTEGGIA SPESSO IN SPIAGGIA" },
    { category: "Corea del Sud: Età", solution: "TRADIZIONALMENTE UNA PERSONA HA UN ANNO GIÀ ALLA NASCITA" },
    { category: "Brasile: Isola dei Serpenti", solution: "ACCESSO VIETATO PERCHÉ POPOLATA DA VIPERE TRA LE PIÙ VELENOSE" },
    { category: "Canada: Hockey", solution: "IN INVERNO I LAGHI GHIACCIATI DIVENTANO PISTE NATURALI" },
    { category: "India: Holi Festival", solution: "FESTA DI PRIMAVERA IN CUI CI SI LANCIA POLVERI COLORATE" },
    { category: "Giappone: Capsule Hotel", solution: "MICRO ALLOGGI GRANDI QUANTO UN LETTO SINGOLO" },
    { category: "Repubblica Ceca: Birra", solution: "ESISTONO CENTRI BENESSERE DOVE SI FA IL BAGNO NELLA BIRRA" },
    { category: "Malesia: Durian", solution: "FRUTTO VIETATO IN HOTEL E METRO PER IL SUO ODORE PUNGENTE" },
    { category: "Argentina: Gnocchi", solution: "PER TRADIZIONE SI MANGIANO IL VENTINOVE DEL MESE CON SOLDI SOTTO IL PIATTO" },
    { category: "New Mexico: Roswell", solution: "CITTÀ FAMOSA PER IL PRESUNTO INCIDENTE UFO DEL MILLENOVECENTOQUARTANTASETTE" },
    { category: "Cina: Panda", solution: "ALCUNI ADDETTI VENGONO PAGATI PER COCCOLARE I CUCCIOLI" },
    { category: "Francia: Baguette", solution: "NON SI TAGLIA MA SI SPEZZA CON LE MANI SECONDO LA TRADIZIONE" },
    { category: "Grecia: Piatto", solution: "ROMPERE I PIATTI AI MATRIMONI PORTA FORTUNA AGLI SPOSI" },
    { category: "Marocco: Tè", solution: "VIENE VERSATO DALL'ALTO PER CREARE LA SCHIUMA" },
    { category: "Cambogia: Ragni", solution: "LE TARANTOLE FRITTE SONO UNO SNACK CROCCANTE E COMUNE" },
    { category: "Austria: Villaggio", solution: "HALLSTATT È COSÌ BELLO CHE I CINESI LO HANNO COPIATO" },
    { category: "Svezia: Metro", solution: "LE STAZIONI SONO SCAVATE NELLA ROCCIA COME CAVERNE D'ARTE" },
    { category: "Giappone: Rumore", solution: "RISUCCHIARE IL BRODO È EDUCATO E DIMOSTRA GRADIMENTO" },
    { category: "Kenya: Saluto", solution: "I GUERRIERI MASAI SALTANO IN ALTO PER DARE IL BENVENUTO" },
    { category: "Alaska: Posta", solution: "LE LETTERE VENIVANO CONSEGNATE CON LE SLITTE TRAINATE DAI CANI" },
    { category: "Indonesia: Caffè", solution: "IL KOPI LUWAK È FATTO CON CHICCHI DIGERITI DALLO ZIBETTO" },
    { category: "Germania: Cuscino", solution: "A BERLINO SI ORGANIZZA UNA MAXI BATTAGLIA DI CUSCINI" },
    { category: "Perù: Porcellino", solution: "IL CUY È UN PORCELLINO D'INDIA SERVITO ARROSTO" },
    { category: "Russia: Sorriso", solution: "SORRIDERE AGLI SCONOSCIUTI È VISTO COME UN GESTO SOSPETTO" },
    { category: "USA: Arizona", solution: "A TOMBSTONE SI RIVIVONO I DUELLI DEL VECCHIO WEST" },
    { category: "Tailandia: Acqua", solution: "A CAPODANNO CI SI TIRA SECCHIATE D'ACQUA PER STRADA" },
    { category: "Inghilterra: Corvi", solution: "SE LASCIANO LA TORRE DI LONDRA CADE LA MONARCHIA" },
    { category: "Spagna: Calçots", solution: "CIPOLLE LUNGHE COTTE SUL FUOCO E MANGIATE CON LE MANI" },
    { category: "Polonia: Drago", solution: "UNA STATUA A CRACOVIA SPUTA FUOCO VERO OGNI CINQUE MINUTI" },
    { category: "Belgio: Tappeto", solution: "OGNI DUE ANNI LA PIAZZA SI COPRE DI FIORI FRESCHI" },
    { category: "Canada: Garage", solution: "SPESSO SONO RISCALDATI PER NON FAR CONGELARE L'AUTO" },
    { category: "Giappone: Semaforo", solution: "LA LUCE VERDE A VOLTE È BLU PER TRADIZIONE ANTICA" },
    { category: "Vietnam: Ponte", solution: "IL GOLDEN BRIDGE È SORRETTO DA DUE MANI GIGANTI DI PIETRA" },
    { category: "Italia: Finestrino", solution: "A FIRENZE SI VENDEVA VINO DA PICCOLE FINESTRE NEL MURO" },
    { category: "USA: Texas", solution: "C'È UN RANCH CON LE AUTO PIANTATE NEL TERRENO" },
    { category: "Mongolia: Gher", solution: "LE CASE SONO TENDE ROTONDE FACILI DA SMONTARE E SPOSTARE" },
    { category: "Islanda: Piscine naturali", solution: "L'ACQUA GEOTERMICA CALDA PERMETTE DI FARE IL BAGNO ANCHE SOTTO LA NEVE" },
    { category: "Corea del Sud: Caffè all'uovo", solution: "UNA BEVANDA TRADIZIONALE PREPARATA SBATTENDO UN TUORLO NEL CAFFÈ" },

    // === INIZIO: FRASI MUSICA (Con TITOLO separato) ===
    { category: "Vasco Rossi", solution: "L'ACCETTAZIONE CHE LA VITA VA VISSUTA ANCHE SENZA CAPIRLA", song_title: "UN SENSO" },
    { category: "Ligabue", solution: "VITE SOSPESE CHE VIAGGIANO NELLA NOTTE SENZA META", song_title: "CERTE NOTTI" },
    { category: "Maneskin", solution: "RIBELLIONE GIOVANILE CONTRO REGOLE E CONVENZIONI", song_title: "ZITTI E BUONI" },
    { category: "Franco Battiato", solution: "LA PROMESSA DI PROTEGGERE CHI SI AMA DA OGNI MALE", song_title: "LA CURA" },
    { category: "Adriano Celentano", solution: "LA MALINCONIA DI UN'ESTATE PASSATA IN SOLITUDINE", song_title: "AZZURRO" },
    { category: "Tiziano Ferro", solution: "IL DOLORE PROFONDO LASCIATO DA UN ADDIO INSPIEGABILE", song_title: "SERE NERE" },
    { category: "Laura Pausini", solution: "LA TRISTEZZA DI UN PRIMO AMORE CHE PARTE IN TRENO", song_title: "LA SOLITUDINE" },
    { category: "John Lennon", solution: "IL SOGNO DI UN MONDO UNITO E PACIFICO SENZA CONFINI", song_title: "IMAGINE" },
    { category: "Domenico Modugno", solution: "L'EUFORIA DI SENTIRSI LIBERI COME SE SI POTESSE VOLARE", song_title: "NEL BLU DIPINTO DI BLU" },
    { category: "Mahmood", solution: "IL CONFLITTO TRA SUCCESSO IDENTITÀ E UN PADRE ASSENTE", song_title: "SOLDI" },
    { category: "Lucio Battisti", solution: "RICORDI POETICI DELL'INFANZIA E DI UN AMORE INGENUO", song_title: "I GIARDINI DI MARZO" },
    { category: "Annalisa", solution: "LA NECESSITÀ DI ESSERE ONESTI CON SÉ STESSI", song_title: "SINCERAMENTE" },
    { category: "Queen", solution: "L'AMMISSIONE DRAMMATICA DI UN UOMO CONDANNATO", song_title: "BOHEMIAN RHAPSODY" },
    { category: "883", solution: "LA NOSTALGIA DEI MITI D'INFANZIA SCOMPARSI", song_title: "HANNO UCCISO L'UOMO RAGNO" },
    { category: "Claudio Baglioni", solution: "IL RICORDO VIVO DEL PRIMO GRANDE AMORE GIOVANILE", song_title: "QUESTO PICCOLO GRANDE AMORE" },
    { category: "Fabrizio De André", solution: "LA BELLEZZA CHE PUÒ NASCERE DAGLI ULTIMI E DAGLI EMERGINATI", song_title: "VIA DEL CAMPO" },
    { category: "Rino Gaetano", solution: "LA SPERANZA CHE TUTTO MIGLIORI NONOSTANTE LE CONTRADDIZIONI SOCIALI", song_title: "MA IL CIELO È SEMPRE PIÙ BLU" },
    { category: "Ultimo", solution: "I PICCOLI GESTI CHE RENDONO INDIMENTICABILE UNA PERSONA AMATA", song_title: "I TUOI PARTICOLARI" },
    { category: "Giorgia", solution: "RICORDI CHE RIEMERGONO DOLOROSI E NITIDI", song_title: "GOCCE DI MEMORIA" },
    { category: "Marco Mengoni", solution: "DIFENDERE CIÒ CHE CONTA DAVVERO DAI GIUDIZI DEL MONDO", song_title: "L'ESSENZIALE" },
    { category: "Jovanotti", solution: "UNA DEDICA TOTALE CHE METTE L'AMATA AL CENTRO DELL'UNIVERSO", song_title: "A TE" },
    { category: "Pino Daniele", solution: "RITRATTO AGRODOLCE DI NAPOLI TRA BELLEZZA E DISINCANTO", song_title: "NAPULE È" },
    { category: "The Kolors", solution: "NOSTALGIA DELLE ESTATI PASSATE IN STILE ANNI OTTANTA", song_title: "ITALODISCO" },
    { category: "Elodie", solution: "L'EMOZIONE CHE TRAVOLGE E FA PERDERE L'EQUILIBRIO", song_title: "VERTIGINE" },
    { category: "Zucchero", solution: "OMAGGIO ALLE DONNE FORTI E COMPLICATE", song_title: "DONNE" },
    { category: "Renato Zero", solution: "LA VITA COME SPETTACOLO CHE DEVE CONTINUARE SEMPRE", song_title: "IL CARROZZONE" },
    { category: "Ghali", solution: "UN DIALOGO CON UN ALIENO PER RACCONTARE ACCOGLIENZA E MERAVIGLIA", song_title: "CASA MIA" },
    { category: "Francesco De Gregori", solution: "DUE AMANTI IN FUGA DALLE REGOLE DEL CIRCO", song_title: "LA DONNA CANNONE" },
    { category: "Mia Martini", solution: "FRAGILITÀ FEMMINILE DAVANTI ALL'EGOISMO MASCHILE", song_title: "GLI UOMINI NON CAMBIANO" },
    { category: "Eros Ramazzotti", solution: "IMMENSA GRATITUDINE VERSO LA PERSONA AMATA", song_title: "PIÙ BELLA COSA" },
    { category: "Antonello Venditti", solution: "LE STORIE D'AMORE VERE NON FINISCONO MAI DAVVERO", song_title: "AMICI MAI" },
    { category: "Lucio Dalla", solution: "LETTERA A UN AMICO PER AFFRONTARE IL FUTURO SENZA PAURA", song_title: "L'ANNO CHE VERRÀ" },
    { category: "Gianna Nannini", solution: "L'AMORE VISSUTO NELLA PARTE PIÙ PROFONDA DELL'ANIMA", song_title: "SEI NELL'ANIMA" },
    { category: "Pinguini Tattici Nucleari", solution: "ACCETTARE IL PROPRIO RUOLO ANCHE SE NON DA PROTAGONISTA", song_title: "RINGO STARR" },
    { category: "Gianni Morandi", solution: "SCUSE INGENUE PER INCONTRARSI DI NASCOSTO", song_title: "FATTI MANDARE DALLA MAMMA" },
    { category: "Negramaro", solution: "LASCIARE ANDARE IL DOLORE DEL PASSATO PER CONTINUARE A VIVERE", song_title: "MENTRE TUTTO SCORRE" },
    { category: "Geolier", solution: "CHIUDERE UNA RELAZIONE TOSSICA PER IL BENE DI ENTRAMBI", song_title: "I P' ME TU P' TE" },
    { category: "Mina", solution: "CHIUDERE UNA STORIA PRIMA DI SOFFRIRE TROPPO", song_title: "SE TELEFONANDO" },
    { category: "Michael Jackson", solution: "TRASFORMARE LA PAURA IN UN BALLO ICONICO", song_title: "THRILLER" },
    { category: "Whitney Houston", solution: "PROMESSA D'AMORE ETERNO NONOSTANTE UN ADDIO DOLOROSO", song_title: "I WILL ALWAYS LOVE YOU" },
    { category: "Cesare Cremonini", solution: "LIBERTÀ GIOVANILE DI CORRERE SPENSIERATI SUI COLLI", song_title: "CINQUANTA SPECIAL" },
    { category: "Loredana Bertè", solution: "ORGOGLIOSA AFFERMAZIONE DELLA PROPRIA NATURA RIBELLE", song_title: "NON SONO UNA SIGNORA" },
    { category: "Pooh", solution: "TIMORE CHE LA ROUTINE SPENGA LA PASSIONE", song_title: "CHI FERMERÀ LA MUSICA" },
    { category: "Arisa", solution: "IMPORTANZA DELLA SINCERITÀ IN UNA RELAZIONE", song_title: "SINCERITÀ" },
    { category: "Irama", solution: "VICINANZA ETERNA ANCHE OLTRE LA MORTE", song_title: "OVUNQUE SARAI" },
    { category: "Mr. Rain", solution: "TROVARE FORZA CONDIVIDENDO LE PROPRIE FRAGILITÀ", song_title: "SUPEREROI" },
    { category: "Raffaella Carrà", solution: "VIVERE AMORE E LIBERTÀ SENZA TABÙ", song_title: "TANTI AUGURI" },
    { category: "Toto Cutugno", solution: "ORGOGLIO DI ESSERE ITALIANI TRA PREGI E DIFETTI", song_title: "L'ITALIANO" },
    { category: "Umberto Tozzi", solution: "UNA DICHIARAZIONE D'AMORE INTENSA DIVENTATA UN CLASSICO ITALIANO", song_title: "TI AMO" },
    { category: "Beatles", solution: "RIMPIANTO PER UN PASSATO PIÙ SEMPLICE E LONTANO", song_title: "YESTERDAY" },
    { category: "Rolling Stones", solution: "FRUSTRAZIONE DI NON OTTENERE CIÒ CHE SI DESIDERA", song_title: "SATISFACTION" },
    { category: "Ricchi e Poveri", solution: "LE EMOZIONI CHE CONFONDONO QUANDO NASCE UN AMORE", song_title: "SARÀ PERCHÉ TI AMO" },
    { category: "Emma Marrone", solution: "UNA DENUNCIA DELLE DIFFICOLTÀ DEL PAESE E DELLA FORZA DI RESISTERE NONOSTANTE TUTTO", song_title: "NON È L'INFERNO" },
    { category: "Alessandra Amoroso", solution: "LA FORZA DI RIALZARSI SEMPRE", song_title: "COMUNQUE ANDARE" },
    { category: "Max Pezzali", solution: "NOSTALGIA DELLE AMICIZIE E DELLE AVVENTURE GIOVANILI", song_title: "GLI ANNI" },
    { category: "Caparezza", solution: "CRITICA AL DIVERTIMENTO FORZATO DELLA VITA NOTTURNA", song_title: "FUORI DAL TUNNEL" },
    { category: "Fabri Fibra", solution: "SENSAZIONE DI ESSERE ESCLUSI DAL SUCCESSO DEGLI ALTRI", song_title: "TRANNE TE" },
    { category: "J-Ax e Fedez", solution: "L'OSSESSIONE DI CONDIVIDERE TUTTO SUI SOCIAL", song_title: "VORREI MA NON POSTO" },
    { category: "Coez", solution: "IL VUOTO QUANDO MANCA CHI DAVA COLORE ALLA VITA", song_title: "LA MUSICA NON C'È" },
    { category: "Gazzelle", solution: "LA FINE DOLOROSA CHE LASCIA SEGNI PROFONDI", song_title: "DESTRI" },
    { category: "Blanco", solution: "SENTIMENTI COSÌ INTENSI DA TOGLIERE IL CONTROLLO", song_title: "BRIVIDI" },
    { category: "Madame", solution: "ANCHE IN UN AMORE SBAGLIATO RESTA QUALCOSA DI BUONO", song_title: "IL BENE NEL MALE" },
    { category: "Rose Villain", solution: "ATTRAZIONE ESPLOSIVA PER QUALCUNO CHE FARÀ SOFFRIRE", song_title: "CLICK BOOM" },
    { category: "Biagio Antonacci", solution: "RIMPIANTO PER UN AMORE MAI VISSUTO FINO IN FONDO COME SI SPERAVA", song_title: "SE IO SE LEI" },
    { category: "Nek", solution: "L'IMPOSSIBILITÀ DI DIMENTICARE UNA EX IMPORTANTE", song_title: "LAURA NON C'È" },
    { category: "Tananai", solution: "AMORE DIVISO E DOLOROSO SULLO SFONDO DELLA GUERRA", song_title: "TANGO" },
    { category: "Dargen D'Amico", solution: "BALLARE PER IGNORARE TEMPORANEAMENTE I PROBLEMI", song_title: "DOVE SI BALLA" },
    { category: "Colapesce Dimartino", solution: "TRISTEZZA NASCOSTA DIETRO UN MOTIVETTO LEGGERO", song_title: "MUSICA LEGGERISSIMA" },
    { category: "Edoardo Bennato", solution: "INVITO A CREDERE NELLA FANTASIA CONTRO LE REGOLE ADULTE", song_title: "L'ISOLA CHE NON C'È" },
    { category: "Francesco Gabbani", solution: "SATIRA SULL'UOMO OCCIDENTALE ALLA RICERCA DI SPIRITUALITÀ DI MODA", song_title: "OCCIDENTALI'S KARMA" },
    { category: "Le Vibrazioni", solution: "DEDICA A UNA DONNA MISTERIOSA INCONTRATA PER CASO", song_title: "DEDICATO A TE" },
    { category: "Irene Grandi", solution: "DESIDERIO IMPULSIVO DI MANDARE TUTTO IN FUMO PUR DI VIVERE UN AMORE TRAVOLGENTE", song_title: "BRUCI LA CITTÀ" },
    { category: "Carmen Consoli", solution: "ADDIO MALINCONICO SOTTO LA PIOGGIA IN STAZIONE", song_title: "L'ULTIMO BACIO" },
    { category: "Elisa", solution: "SUPERARE LE DIFFICOLTÀ DI COMUNICAZIONE IN COPPIA", song_title: "GLI OSTCOLI DEL CUORE" },
    { category: "Negrita", solution: "LA SPERANZA CHE FIORISCE NEI MOMENTI PIÙ DURI", song_title: "MAGNOLIA" },
    { category: "Tiromancino", solution: "DUE DESTINI CHE SI INCONTRANO COME FOSSE SCRITTO", song_title: "DUE DESTINI" },
    { category: "Subsonica", solution: "ACCETTARE I PROPRI ERRORI COME PARTE DELLA CRESCITA", song_title: "TUTTI I MIEI SBAGLI" },
    { category: "Articolo 31", solution: "LA PROMESSA DI CAMBIARE RIMANDATA A DOMANI", song_title: "DOMANI SMETTO" },
    { category: "Lunapop", solution: "LA SENSAZIONE CHE STIA NASCENDO UN GRANDE AMORE", song_title: "QUALCOSA DI GRANDE" },
    { category: "Bob Marley", solution: "CONSOLARE UNA DONNA RICORDANDO LA FORZA NATA NEI MOMENTI DIFFICILI", song_title: "NO WOMAN NO CRY" },
    { category: "Madonna", solution: "L'EMOZIONE PURA DI SENTIRSI AMATI COME LA PRIMA VOLTA", song_title: "LIKE A VIRGIN" },
    { category: "Elvis Presley", solution: "UN SENTIMENTO IRRESISTIBILE A CUI NON SI PUÒ SFUGGIRE", song_title: "CAN'T HELP FALLING IN LOVE" },
    { category: "Frank Sinatra", solution: "ORGOGLIO DI AVER VISSUTO SEGUENDO SOLO LE PROPRIE REGOLE", song_title: "MY WAY" },
    { category: "ABBA", solution: "LA DIFFICILE ATTRAZIONE VERSO UN EX CHE TORNA", song_title: "MAMMA MIA" },
    { category: "Adele", solution: "TENTATIVO DI RICONCILIARSI DOPO ANNI DI SILENSIO", song_title: "HELLO" },
    { category: "Coldplay", solution: "LE STELLE COME OMAGGIO POETICO ALLA PERSONA AMATA", song_title: "YELLOW" },
    { category: "U2", solution: "AMORE CHE NON FUNZIONA NÉ INSIEME NÉ SEPARATI", song_title: "WITH OR WITHOUT YOU" },
    { category: "Pink Floyd", solution: "LA MANCANZA DI UN AMICO PERSO NELL'ALIENAZIONE", song_title: "WISH YOU WERE HERE" },
    { category: "David Bowie", solution: "SENTIRSI EROI ANCHE SOLO PER UN GIORNO", song_title: "HEROES" },
    { category: "Prince", solution: "FINE DI UN AMORE RACCONTATA COME PIOGGIA COLORATA", song_title: "PURPLE RAIN" },
    { category: "Lady Gaga", solution: "ACCOGLIERE CON ORGOGLIO LA PROPRIA DIVERSITÀ", song_title: "BORN THIS WAY" },
    { category: "Ed Sheeran", solution: "ATTRAZIONE FISICA IRRESISTIBILE CHE NASCE DAI DETTAGLI DEL CORPO DELL'ALTRO", song_title: "SHAPE OF YOU" },
    { category: "Shakira", solution: "RIVINCITA DI UNA DONNA TRADITA TRASFORMATA IN SUCCESSO", song_title: "BZRP MUSIC SESSIONS VOL CINQUANTATRE" },
    { category: "Dua Lipa", solution: "BALLARE PER DIMENTICARE I PROBLEMI SENTIMENTALI", song_title: "DANCE THE NIGHT" },
    { category: "Miley Cyrus", solution: "SCOPRIRE DI POTER BASTARE A SÉ STESSI", song_title: "FLOWERS" },
    { category: "Taylor Swift", solution: "IGNORARE LE CRITICHE E CONTINUARE A BALLARE", song_title: "SHAKE IT OFF" },
    { category: "Rihanna", solution: "MOSTRARE LA PROPRIA LUCE COME UN DIAMANTE", song_title: "DIAMONDS" },
    { category: "Beyoncé", solution: "RIMPROVERO A CHI NON SI È IMPEGNATO DAVVERO", song_title: "SINGLE LADIES" },
    { category: "Katy Perry", solution: "RITROVARE LA FORZA DOPO OGNI SCONFITTA", song_title: "ROAR" },
    { category: "Avril Lavigne", solution: "IL BISOGNO DI CAPIRE QUALCUNO CHE NASCONDE CIÒ CHE PROVA DAVVERO", song_title: "COMPLICATED" },

    // === INIZIO: FRASI MISTERO (Classificate con sottocategorie) ===
    { category: "Mistero Domestico", solution: "DOVE FINISCONO I CALZINI SPAIATI NELLA LAVATRICE" },
    { category: "Mistero Tecnologico", solution: "PERCHÉ IL CAVO DELLE CUFFIE SI ANNODA SEMPRE IN TASCA" },
    { category: "Mistero Culinario", solution: "CHI HA DECISO CHE L'ANANAS PUÒ ANDARE SULLA PIZZA" },
    { category: "Mistero del Corpo Umano", solution: "PERCHÉ CI SVEGLIAMO STANCHI DOPO AVER DORMITO TANTO" },
    { category: "Mistero Animale", solution: "COSA FISSANO I GATTI QUANDO GUARDO IL MURO VUOTO" },
    { category: "Mistero Quotidiano", solution: "L'ALTRA CORSIA SCORRE SEMPRE PIÙ VELOCE DELLA TUA" },
    { category: "Mistero della Fisica", solution: "LA FETTA BISCOTTATA CADE SEMPRE DAL LATO IMBURRATO" },
    { category: "Mistero della Mente", solution: "ENTRARE IN UNA STANZA E SCORDARE PERCHÉ CI SIAMO ANDATI" },
    { category: "Mistero Storico", solution: "COME HANNO FATTO A COSTRUIRE LE PIRAMIDI SENZA GRU" },
    { category: "Mistero del Cinema", solution: "COME FANNO I POPCORN A FINIRE PRIMA DELL'INIZIO DEL FILM" },
    { category: "Mistero Sociale", solution: "PERCHÉ LO SBADIGLIO È COSÌ INCREDIBILMENTE CONTAGIOSO" },
    { category: "Mistero Tecnologico", solution: "LA CHIAVETTA USB NON ENTRA MAI AL PRIMO TENTATIVO" },
    { category: "Mistero Naturale", solution: "È NATO PRIMA L'UOVO O LA GALLINA" },
    { category: "Mistero dell'Arte", solution: "CHI STA GUARDANDO E PERCHÉ SORRIDE LA GIOCONDA" },
    { category: "Mistero Geografico", solution: "COSA SUCCEDE DAVVERO NEL TRIANGOLO DELLE BERMUDA" },
    { category: "Mistero dei Viaggi", solution: "PERCHÉ AL RITORNO I VESTITI NON ENTRANO PIÙ IN VALIGIA" },
    { category: "Mistero del Tempo", solution: "I MINUTI PASSANO PIÙ LENTI QUANDO SI ASPETTA QUALCUNO" },
    { category: "Mistero Leggendario", solution: "C'È DAVVERO UN MOSTRO NEL LAGO DI LOCH NESS" },
    { category: "Mistero della Mente", solution: "AVERE UNA PAROLA SULLA PUNTA DELLA LINGUA E NON DIRLA" },
    { category: "Mistero Meteorologico", solution: "PIOVE SEMPRE APPENA HAI FINITO DI LAVARE LA MACCHINA" },
    { category: "Mistero Preistorico", solution: "PERCHÉ SI SONO ESTINTI I DINOSAURI ALL'IMPROVVISO" },
    { category: "Mistero Domestico", solution: "DOVE SPARISCONO I COPERCHI DEI CONTENITORI DI PLASTICA" },
    { category: "Mistero Spaziale", solution: "SIAMO SOLI NELL'UNIVERSO O CI SONO ALTRE FORME DI VITA" },
    { category: "Mistero del Tempo", solution: "PERCHÉ IL WEEKEND SEMBRA DURARE MOLTO MENO DELLA SETTIMANA" },
    { category: "Mistero della Natura", solution: "PERCHÉ LE ZANZARE RONZANO PROPRIO VICINO ALL'ORECCHIO" },
    { category: "Mistero Archeologico", solution: "A COSA SERVIVANO LE PIETRE GIGANTI DI STONEHENGE" },
    { category: "Mistero Letterario", solution: "SHERLOCK HOLMES È ESISTITO DAVVERO O È SOLO FANTASIA" },
    { category: "Mistero del Corpo Umano", solution: "A COSA SERVE AVERE IL SINGHIOZZO ALL'IMPROVVISO" },
    { category: "Mistero Sociale", solution: "PERCHÉ CI SI SALUTA DICENDO COME STAI SENZA ASCOLTARE" },
    { category: "Mistero Domestico", solution: "IL TELEFONO SQUILLA SEMPRE QUANDO SEI SOTTO LA DOCCIA" },
    { category: "Mistero della Moda", solution: "CHI DECIDE COSA ANDRÀ DI MODA LA PROSSIMA STAGIONE" },
    { category: "Mistero Leggendario", solution: "LA CITTÀ DI ATLANTIDE È SOMMERSA O NON ESISTE" },
    { category: "Mistero Medico", solution: "PERCHÉ LE ISTRUZIONI DEI MEDICINALI SONO IMPOSSIBILI DA RIPIEGARE" },
    { category: "Mistero Sentimentale", solution: "PERCHÉ CI INNAMORIAMO PROPRIO DI CHI CI FA SOFFRIRE" },
    { category: "Mistero Onirico", solution: "PERCHÉ SOGNIAMO DI CADERE NEL VUOTO O DI VOLARE" },
    { category: "Mistero Ristorante", solution: "IL TAVOLO VICINO VIENE SEMPRE SERVITO PRIMA DEL TUO" },
    { category: "Mistero Animale", solution: "PERCHÉ I CANI INSEGUONO LA PROPRIA CODA GIRANDO IN TONDO" },
    { category: "Mistero Domestico", solution: "DA DOVE ARRIVA TUTTA LA POLVERE CHE SI FORMA IN CASA" },
    { category: "Mistero Musicale", solution: "PERCHÉ CERTE CANZONI CI RESTANO IN TESTA PER GIORNI" },
    { category: "Mistero Storico", solution: "CHI ERA DAVVERO L'UOMO CON LA MASCHERA DI FERRO" },
    { category: "Mistero Tecnologico", solution: "PREMERE I TASTI PIÙ FORTE QUANDO LE PILE SONO SCARICHE" },
    { category: "Mistero Quotidiano", solution: "PERCHÉ LE IDEE MIGLIORI VENGONO MENTRE CI LAVIAMO" },
    { category: "Mistero Botanico", solution: "PERCHÉ IL QUADRIFOGLIO È COSÌ RARO DA TROVARE NEL PRATO" },
    { category: "Mistero Quotidiano", solution: "LA FILA CHE SCEGLI È SEMPRE LA PIÙ LENTA DI TUTTE" },
    { category: "Mistero Infantile", solution: "COME FANNO I BAMBINI AD AVERE TUTTA QUELL'ENERGIA" },
    { category: "Mistero Astronomico", solution: "PERCHÉ VEDIAMO SEMPRE E SOLO LA STESSA FACCIA DELLA LUNA" },
    { category: "Mistero Storico", solution: "QUALE SEGRETO NASCONDE LA SFINGE TRA LE ZAMPE" },
    { category: "Mistero Culinario", solution: "PERCHÉ CADONO SEMPRE BRICIOLE OVUNQUE QUANDO TAGLI IL PANE" },
    { category: "Mistero Domestico", solution: "LE CHIAVI SONO SEMPRE NELL'ULTIMO POSTO DOVE GUARDI" },
    { category: "Mistero del Corpo Umano", solution: "PERCHÉ ABBIAMO ANCORA IL DENTE DEL GIUDIZIO SE FA MALE" },
    { category: "Mistero della Percezione", solution: "IL BLU CHE VEDO IO È UGUALE AL BLU CHE VEDI TU" },
    { category: "Mistero Burocratico", solution: "PERCHÉ LA PENNA LEGATA ALLO SPORTELLO NON SCRIVE MAI" },
    { category: "Mistero Culinario", solution: "PERCHÉ IL CIBO IN VOLO HA UN SAPORE DIVERSO" },
    { category: "Mistero Archeologico", solution: "CHI HA DISEGNATO LE LINEE GIGANTI NEL DESERTO DI NAZCA" },
    { category: "Mistero del Corpo Umano", solution: "PERCHÉ NON POSSIAMO FARCI IL SOLLETICO DA SOLI" },
    { category: "Mistero delle Emozioni", solution: "PERCHÉ CI VIENE LA PELLE D'OCA QUANDO ABBIAMO PAURA" },
    { category: "Mistero Estivo", solution: "PERCHÉ LA SABBIA ENTRA OVUNQUE ANCHE SE STAI ATTENTO" },
    { category: "Mistero Fisico", solution: "PERCHÉ I CUBETTI DI GHIACCIO SONO SCIVOLOSI E FREDDI" },
    { category: "Mistero Familiare", solution: "COME FANNO I NONNI A SVEGLIARSI SEMPRE COSÌ PRESTO" },
    { category: "Mistero Geografico", solution: "COME SI FORMANO LE OASI IN MEZZO A TUTTA QUELLA SABBIA" },
    { category: "Mistero Cospirativo", solution: "COSA NASCONDONO NELL'AREA CINQUANTUNO NEL DESERTO" },
    { category: "Mistero Fisico", solution: "COME FA IL DENTIFRICIO A USCIRE A STRISCE DAL TUBETTO" },
    { category: "Mistero del Benessere", solution: "PERCHÉ RIDERE CI FA SENTIRE MEGLIO ANCHE FISICAMENTE" },
    { category: "Mistero Acustico", solution: "PERCHÉ SENTIAMO DEI FISCHI NELLE ORECCHIE QUANDO C'È SILENZIO" },
    { category: "Mistero Familiare", solution: "I GEMELLI HANNO DAVVERO UNA CONNESSIONE TELEPATICA" },
    { category: "Mistero Botanico", solution: "LE PIANTE SENTONO DOLORE O PAURA QUANDO VENGONO TAGLIATE" },
    { category: "Mistero Leggendario", solution: "DOVE SI TROVA LA LEGGENDARIA CITTÀ DI ELDORADO" },
    { category: "Mistero Culinario", solution: "CHI FA I BUCHI DENTRO L'EMMENTAL MENTRE MATURA" },
    { category: "Mistero Scolastico", solution: "PERCHÉ LA PUNTA SI SPEZZA SEMPRE APPENA L'HAI TEMPERATA" },
    { category: "Mistero Archeologico", solution: "PERCHÉ LE STATUE DELL'ISOLA DI PASQUA GUARDANO L'INTERNO" },
    { category: "Mistero Animale", solution: "COME FANNO LE FORMICHE A SAPERE DOVE HAI LASCIATO LO ZUCCHERO" },
    { category: "Mistero del Corpo Umano", solution: "PERCHÉ LE IMPRONTE DIGITALI SONO UNICHE PER OGNUNO" },
    { category: "Mistero Animale", solution: "COME FA IL CAMALEONTE A CAMBIARE COLORE IN BASE ALL'UMORE" },
    { category: "Mistero Oceanico", solution: "COSA C'È SUL FONDO DELLA FOSSA DELLE MARIANNE" },
    { category: "Mistero della Mente", solution: "PERCHÉ CI SEMBRA DI AVER GIÀ VISSUTO CERTI MOMENTI" },
    { category: "Mistero Spaziale", solution: "QUANTE STELLE CI SONO DAVVERO NELLA VIA LATTEA" },
    { category: "Mistero Notturno", solution: "PERCHÉ LE LENZUOLA SI ATTORCIGLIANO SEMPRE SU SE STESSE" },
    { category: "Mistero Fisico", solution: "PERCHÉ LE BOLLE DI SAPONE SONO SEMPRE ROTONDE" },
    { category: "Mistero Sociale", solution: "COME FA IL CAMERIERE A RICORDARE TUTTO SENZA SCRIVERE" },
    { category: "Mistero Biblico", solution: "DOVE SI TROVA OGGI L'ARCA DELL'ALLEANZA" },
    { category: "Mistero Animale", solution: "PERCHÉ I PICCIONI MUOVONO LA TESTA AVANTI E INDIETRO" },
    { category: "Mistero Culinario", solution: "IL KETCHUP NON ESCE MAI E POI ESCE TUTTO INSIEME" },
    { category: "Mistero Animale", solution: "LE ZEBRE SONO BIANCHE A STRISCE NERE O VICEVERSA" },
    { category: "Mistero Storico", solution: "CHI È STATO IL PRIMO UOMO A SCOPRIRE COME ACCENDERE IL FUOCO" },
    { category: "Mistero Animale", solution: "PERCHÉ IL CANGURO HA UNA TASCA SULLA PANCIA PER IL CUCCIOLO" },
    { category: "Mistero Acustico", solution: "PERCHÉ LA VOCE TORNA INDIETRO COME ECO SOLO IN CERTI LUOGHI" },
    { category: "Mistero del Corpo Umano", solution: "PERCHÉ LA MAGGIOR PARTE DELLE PERSONE USA LA MANO DESTRA" },
    { category: "Mistero Animale", solution: "PERCHÉ IL PANDA MANGIA SOLO BAMBÙ SE È UN ORSO" },
    { category: "Mistero Olfattivo", solution: "PERCHÉ L'ODORE DELL'ASFALTO BAGNATO È COSÌ BUONO" },
    { category: "Mistero del Corpo Umano", solution: "A COSA SERVE L'OMBELICO UNA VOLTA CHE SIAMO NATI" },
    { category: "Mistero Animale", solution: "I PESCI BEVONO L'ACQUA SALATA IN CUI NUOTANO O NO" },
    { category: "Mistero Scientifico", solution: "COSA RENDEVA IL CERVELLO DI EINSTEIN DIVERSO DAGLI ALTRI" },
    { category: "Mistero Fisico", solution: "PERCHÉ L'AGO DELLA BUSSOLA INDICA SEMPRE IL NORD MAGNETICO" },
    { category: "Mistero Naturale", solution: "COME FANNO LE LUCCIOLE A FARE LUCE CON IL LORO CORPO" },
    { category: "Mistero Culinario", solution: "PERCHÉ CI ESCONO LE LACRIME QUANDO TAGLIAMO LA CIPOLLA" },
    { category: "Mistero Leggendario", solution: "C'È DAVVERO UNA PENTOLA D'ORO ALLA FINE DELL'ARCOBALENO" },
    { category: "Mistero del Corpo Umano", solution: "PERCHÉ I CAPELLI DIVENTANO BIANCHI QUANDO INVECCHIAMO" },
    { category: "Mistero Chimico", solution: "PERCHÉ IL CAFFÈ CI SVEGLIA E CI DÀ ENERGIA AL MATTINO" },
    { category: "Mistero Filosofico", solution: "LA FORTUNA ESISTE DAVVERO O È SOLO UNA QUESTIONE DI CASO" },
    { category: "Mistero Filosofico", solution: "QUAL È IL VERO SENSO DELLA NOSTRA ESISTENZA" },
];


// --- 2. ROUND CRUCIVERBA (ex CruciRuota) ---
const cruciVerbaDB = [
    // Inserire qui i dati del cruciverba quando disponibili
];


// --- 3. ROUND TRE SOLUZIONI (ex Triplete) ---
const treSoluzioniDB = [
    {
        category: "Collezionismo",
        phrases: [
            "ANTICHE MONETE DI IMMENSO VALORE",
            "IL RARO FRANCOBOLLO GRONCHI ROSA",
            "LE RICERCATE CARTE DEI POKÉMON"
        ]
    }
];

// --- 4. ROUND FINALE ---
const finalRoundDB = [
    {
        phrases: [
            "L'ULTIMO RIGORE DI UNA FINALE", 
            "IL COLOSSEO DI ROMA", 
            "UN VIAGGIO IN MONGOLFIERA" 
        ]
    }
];

// --- 5. ROUND VELOCE (Mantenuto ma svuotato e non usato, come richiesto) ---
const openingRoundDB = [];